version: '3.8'

services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    environment:
          - DATABASE_USER=test_user
          - DATABASE_PASSWORD=test_password
          - DATABASE_NAME=test_db
          - DATABASE_HOST=test_db
          - DATABASE_PORT=5432
          - JWT_SECRET=test_secret
    depends_on:
      test_db:
        condition: service_healthy
    networks:
      - internal

  test_db:
    image: postgres:13
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_db" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  test-runner:
    build: .
    container_name: test-runner
    environment:
      - DATABASE_USER=test_user
      - DATABASE_PASSWORD=test_password
      - DATABASE_NAME=test_db
      - DATABASE_HOST=test_db
      - DATABASE_PORT=5432
    depends_on:
      test_db:
        condition: service_healthy
      avito-shop-service:
        condition: service_started
    networks:
      - internal
    command: [ "go", "test", "-v", "./internal/integration" ]

volumes:
  pgdata_test:

networks:
  internal:
